### ISSUE TITLE
feat: add Balancer support to the RetryEnabled config

### ISSUE THREAD

**Issue by Abdulsametileri** [Trendyol/kafka-konsumer#120]
Currently, we producing as round-robin, but we need hash some cases, we need to support it asap

**Comment by Abdulsametileri** [comment]
<img width="612" alt="Screenshot 2024-03-27 at 23 47 17" src="https://github.com/Trendyol/kafka-konsumer/assets/19360039/372a0698-e879-4f9b-8d81-96f3e7fadb25">

**Comment by dilaragorum** [comment]
{"level":"DEBUG","time":"2024-03-28T18:03:06.171Z","sourceLocation":"v2@v2.1.9/consumer_base.go:122","message":"Initializing Cronsumer"}
{"level":"DEBUG","time":"2024-03-28T18:03:06.171Z","sourceLocation":"v2@v2.1.9/consumer_base.go:122","message":"Initializing Cronsumer"}
{"level":"DEBUG","time":"2024-03-28T18:03:06.171Z","sourceLocation":"v2@v2.1.9/consumer_base.go:122","message":"Initializing Cronsumer"}
{"level":"DEBUG","time":"2024-03-28T18:03:06.172Z","sourceLocation":"v2@v2.1.9/consumer_base.go:122","message":"Initializing Cronsumer"}
{"level":"DEBUG","time":"2024-03-28T18:03:06.172Z","sourceLocation":"v2@v2.1.9/consumer_base.go:122","message":"Initializing Cronsumer"}
{"level":"DEBUG","time":"2024-03-28T18:03:06.172Z","sourceLocation":"v2@v2.1.9/consumer_base.go:122","message":"Initializing Cronsumer"}

need to enhance this kind of logs messages

**Comment by Abdulsametileri** [comment]
implemented, thanks https://github.com/Trendyol/kafka-konsumer/commit/ac1f317f2f6632ba63f31ba8087f96174d70b9a9
