### ISSUE TITLE
bug: Doesn't try to connect with the next broker

### ISSUE THREAD

**Issue by osemrt** [Trendyol/kafka-konsumer#135]
Hi, I noticed an issue with brokers. 

A set of the Kafka broker list in the application configs is given to increase the availability. 

if the broker list contains invalid brokers, and the app first uses one of those invalid brokers to connect the Kafka, then it halts and doesn't report or print any log about the problem. 

It is expected to reconnect Kafka with the next brokers, but it doesn't.

**Comment by Abdulsametileri** [comment]
We can move this issue to the [segmentio/kafka-go](https://github.com/segmentio/kafka-go)

**Comment by Abdulsametileri** [comment]
- should use 9092 instead of 9093
- give broker list as "," not " ,".

we cannot reproduce the issue but in our local tests, we realized that entering broker values " ," causes problem, we need to implement strings.TrimSpace here, 

let's do it together 💪🏻
