### ISSUE TITLE
write error log when topic is not created

### ISSUE THREAD

**Issue by keremcankabadayi** [Trendyol/kafka-konsumer#59]
```
Reader: kafka.ReaderConfig{
			Brokers:        strings.Split(getConsumerServers(a.Kafka), ","),
			GroupID:        consumerCfg.ConsumerGroup,
			GroupTopics:    consumerCfg.Topics,
			MaxWait:        2 * time.Second,
			CommitInterval: time.Second,
			Logger:         l,
			ErrorLogger:    l,
		},
```

I added logger and error logger. I would be great if we saw log about topic not found or smth.

**Comment by Abdulsametileri** [comment]
Thank you! We can ask this question to the [segmentio-kafkago](https://github.com/segmentio/kafka-go) @keremcankabadayi

**Comment by Abdulsametileri** [comment]
https://github.com/segmentio/kafka-go/issues/1142 here related issue, 
@dilaragorum will also check related pr https://github.com/Trendyol/kafka-konsumer/pull/111

**Comment by Abdulsametileri** [comment]
implemented, thank you for your contribution @keremcankabadayi <3 [commit](https://github.com/Trendyol/kafka-konsumer/commit/ca225fb37872ac0a84143bce75113f483ecd62dd)
