### ISSUE TITLE
Avoid calling NewAPI for multiple times

### ISSUE THREAD

**Issue by mhmtszr** [Trendyol/kafka-konsumer#88]
Right now if we have more than one consumer and apiEnabled is true, for every consumer we are creating new api. Instead we can create the api once and use this API for all consumers.

**Comment by Abdulsametileri** [comment]
API is bounded on a consumer instance when a client wants multiple consumers, currently, it is not possible to support and solve this problem efficiently. 

We implemented another alternative solution for this problem. We have added two new features for this. 

- Firstly, we have added `metricPrefix`. It's basically

```
MetricPrefix is used for prometheus fq name prefix. If not provided, default metric prefix value is kafka_konsumer. Currently, there are two exposed prometheus metrics. processed_messages_total and unprocessed_messages_total So, if default metric prefix used, metrics names are kafka_konsumer_processed_messages_total_current and kafka_konsumer_unprocessed_messages_total_current.
```

- Secondly, we have added a new method called `GetMetricCollectors() []prometheus.Collector` . It's basically
```
GetMetricCollectors for the purpose of making metric collectors available. You can register these collectors on your own http server. Please look at the examples/with-metric-collector directory.
```

We also showed an example of this.

https://github.com/Trendyol/kafka-konsumer/tree/v2/examples/with-metric-collector

This solution is enough to close this issue; what do you think? 🤔
